name: Update GitHub Profile

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    timeout-minutes: 15

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create dist directory
        run: |
          rm -rf dist
          mkdir -p dist

      - name: Generate GitHub Stats
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&hide_title=false&hide_rank=false&show_icons=true&include_all_commits=true&count_private=true&disable_animations=false&theme=dracula&locale=en&hide_border=false
          path: dist/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate GitHub Trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: ${{ github.repository_owner }}
          output_path: dist/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Pacman Contribution Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Check generated files
        run: |
          echo "Generated files:"
          find dist -maxdepth 1 -type f -print

      - name: Push generated files to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update GitHub profile graphs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}